### ISSUE TITLE
Led randomly activating with spectrum effect

### ISSUE THREAD

**Issue by Resaltare** [RanzQ/hyperion-audio-effects#16] opened 2016-03-13 12:48 UTC
Hello,

First congrats on this very cool project!

I have successfully set it up and everyhting is working fine with Vumeter effect.
The spectrum effect however shows spurious display on the gui with leds randomly activating even with no audio output at all! This is not happening with Vumeter.

This happens with default configuration and Rpi CPU load is around 70% (230 leds). I also tried to mess around with effect parameters, especially band-width-exp but to no avail.

Any clue why this happens? Is it by chance linked to issue#5?

Thank you

**Comment by RanzQ** [comment] 2016-03-13 15:56
I've noticed the random blinking too, not sure what causes it. I guess the problem is with gstreamer itself, sending invalid messages. I'll debug it a bit more.

I'm currently writing a new version that uses proto-connection instead of json. I had high cpu usage issues as well with 300 leds (low end pc, not pi though).

**Comment by Resaltare** [comment] 2016-03-13 21:21
Great news! Looking forward to test the new proto connection :)

**Comment by RanzQ** [comment] 2016-03-27 13:24
@Resaltare there's now a proto connection. Since the proto connection only supports sending images, I still need to create a method to convert the led data into images. With a resolution low enough this might perform better than the json version.

I implemented a matrix version of the spectrum effect already though (bars instead of brightness). I'll do some tests if the blinking still occurs.

**Comment by RanzQ** [comment] 2016-04-24 10:02
I'll close this since it seems to be a problem only if too many leds used with json connection.

**Closed by RanzQ** 2016-04-24 10:02 UTC
